//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceSwagger.DataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemById", ReplyAction="http://tempuri.org/IService1/GetItemByIdResponse")]
        Data_Service_Web_Role.Item GetItemById(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemById", ReplyAction="http://tempuri.org/IService1/GetItemByIdResponse")]
        System.Threading.Tasks.Task<Data_Service_Web_Role.Item> GetItemByIdAsync(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemByCategory", ReplyAction="http://tempuri.org/IService1/GetItemByCategoryResponse")]
        Data_Service_Web_Role.Item[] GetItemByCategory(string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemByCategory", ReplyAction="http://tempuri.org/IService1/GetItemByCategoryResponse")]
        System.Threading.Tasks.Task<Data_Service_Web_Role.Item[]> GetItemByCategoryAsync(string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveNewItem", ReplyAction="http://tempuri.org/IService1/SaveNewItemResponse")]
        string SaveNewItem(Data_Service_Web_Role.Item jsonItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveNewItem", ReplyAction="http://tempuri.org/IService1/SaveNewItemResponse")]
        System.Threading.Tasks.Task<string> SaveNewItemAsync(Data_Service_Web_Role.Item jsonItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DataServiceSwagger.DataServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DataServiceSwagger.DataServiceReference.IService1>, DataServiceSwagger.DataServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data_Service_Web_Role.Item GetItemById(string itemId) {
            return base.Channel.GetItemById(itemId);
        }
        
        public System.Threading.Tasks.Task<Data_Service_Web_Role.Item> GetItemByIdAsync(string itemId) {
            return base.Channel.GetItemByIdAsync(itemId);
        }
        
        public Data_Service_Web_Role.Item[] GetItemByCategory(string categoryId) {
            return base.Channel.GetItemByCategory(categoryId);
        }
        
        public System.Threading.Tasks.Task<Data_Service_Web_Role.Item[]> GetItemByCategoryAsync(string categoryId) {
            return base.Channel.GetItemByCategoryAsync(categoryId);
        }
        
        public string SaveNewItem(Data_Service_Web_Role.Item jsonItem) {
            return base.Channel.SaveNewItem(jsonItem);
        }
        
        public System.Threading.Tasks.Task<string> SaveNewItemAsync(Data_Service_Web_Role.Item jsonItem) {
            return base.Channel.SaveNewItemAsync(jsonItem);
        }
    }
}
